#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

: "${TERMUX_BOOTSTRAP_PACKAGE_NAME:=com.termux.rafacodephi}"
: "${TERMUX_BOOTSTRAP_PAGE_SIZE:=16384}"

builder="${TMPDIR:-/tmp}/bootstrap_zip_builder.$$"
generated_root="${ROOT_DIR}/build/generated/rafaelia-bootstrap/common"
trap 'rm -f "$builder"' EXIT

mkdir -p "${generated_root}/bin" "${generated_root}/etc" app/src/main/cpp

cat > "${generated_root}/bin/sh" <<'EOS'
#!/system/bin/sh
# RAFCODEPHI local bootstrap shell generated by CI/actions at build time.
echo "RAFCODEPHI bootstrap shell"
exec /system/bin/sh "$@"
EOS

cat > "${generated_root}/bin/pkg" <<'EOS'
#!/system/bin/sh
# RAFCODEPHI local bootstrap package-manager sentinel generated by CI/actions.
echo "RAFCODEPHI developer bootstrap pkg"
exit 0
EOS

cat > "${generated_root}/bin/busybox" <<'EOS'
#!/system/bin/sh
# RAFCODEPHI local bootstrap compatibility stub generated by CI/actions.
echo "RAFCODEPHI bootstrap busybox stub"
exit 0
EOS

cat > "${generated_root}/bin/proot" <<'EOS'
#!/system/bin/sh
# RAFCODEPHI local bootstrap compatibility stub generated by CI/actions.
echo "RAFCODEPHI bootstrap proot stub"
exit 0
EOS

cat > "${generated_root}/etc/motd" <<'EOS'
RAFCODEPHI bootstrap payload
EOS
chmod 700 "${generated_root}/bin/sh" "${generated_root}/bin/pkg" "${generated_root}/bin/busybox" "${generated_root}/bin/proot"
chmod 600 "${generated_root}/etc/motd"

cc -O2 -std=c11 -Wall -Wextra -Werror scripts/bootstrap_zip_builder.c -o "$builder"
RAF_BOOTSTRAP_SRC_DIR="$generated_root" TERMUX_BOOTSTRAP_PACKAGE_NAME="$TERMUX_BOOTSTRAP_PACKAGE_NAME" TERMUX_BOOTSTRAP_PAGE_SIZE="$TERMUX_BOOTSTRAP_PAGE_SIZE" "$builder" app/src/main/cpp/bootstrap-aarch64.zip aarch64
RAF_BOOTSTRAP_SRC_DIR="$generated_root" TERMUX_BOOTSTRAP_PACKAGE_NAME="$TERMUX_BOOTSTRAP_PACKAGE_NAME" TERMUX_BOOTSTRAP_PAGE_SIZE="$TERMUX_BOOTSTRAP_PAGE_SIZE" "$builder" app/src/main/cpp/bootstrap-arm.zip arm
RAF_BOOTSTRAP_SRC_DIR="$generated_root" TERMUX_BOOTSTRAP_PACKAGE_NAME="$TERMUX_BOOTSTRAP_PACKAGE_NAME" TERMUX_BOOTSTRAP_PAGE_SIZE="$TERMUX_BOOTSTRAP_PAGE_SIZE" "$builder" app/src/main/cpp/bootstrap-i686.zip i686
RAF_BOOTSTRAP_SRC_DIR="$generated_root" TERMUX_BOOTSTRAP_PACKAGE_NAME="$TERMUX_BOOTSTRAP_PACKAGE_NAME" TERMUX_BOOTSTRAP_PAGE_SIZE="$TERMUX_BOOTSTRAP_PAGE_SIZE" "$builder" app/src/main/cpp/bootstrap-x86_64.zip x86_64

echo "RAFCODEPHI bootstraps generated for package=${TERMUX_BOOTSTRAP_PACKAGE_NAME} page_size=${TERMUX_BOOTSTRAP_PAGE_SIZE} payload=${generated_root}"
